language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  # NPM_TOKEN
  - secure: "2K0i8n43cR/DhY+u11/YK01/kOdznGFk3tzgIu1mqXWlaPBHDR/TwP7qlLMBlTjPleGTdJ6caVJkQH3mRRKlXFezWEscLR1dmRWsqrba1mM43YWliRUa1SHmbtvg78hQExNe3mYf5rsinIu3z+oI8jkTsWIFmWTuk0p0LtSevL9RJAQTX89hoAgvTsYJm7fud2hO02IYf8ETvCchD7LitZ9Hv/sKfi46I35uRBg+v/yBYH/vO6bT0TvmDD/OrBpDvHWvINdwhinmoIiZ0fiKYjXhcFHJgy3hz4UpswD11UOAzCy55GOCeKRRIjPsUrsHjVpNBI3vAytCALH5UzryODPTvg43s82drIZB3morec/oJpehCp1AYGAwZQ2r86nLkzmiL6awtLBNIFCSK5hNnReLAbo4U/n47e5gFQ9kuPym/91O0bil1HbvJoC7f9v0Zz+RxOVGt6TyWgWHlD0fLNMSBQ5o1J848z5smc+hLM+i2fgfynZ5QwxfHlT0spoe73otwg6NagzQbQ6/u3qckeSY8xTloe6frYYsY20rBgRWNBSspi5r8HEaLySy8UV7z12DIE2Lpu4JdFoxbseXbNysk/BhHw0D+2qZ0fUGhsArULSSdAzvFHNGzIFcG2/5An0BwodkW4JOK7ll1SlZQxo/8k+eEyGmZxaI6cnGqCk="

install:
- npm install --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/prepack-publish
