language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  # NPM_TOKEN
  - secure: "X2vMb2KJsIYgjVf41HDnjdFGvG2FuKVuHQFguoSaoRFUZwULZq2+y0gx4zX1/47MDsSyZWmIYL0FzsnQEKs0Lr7MsMWNqA6oGkFX+XGmWnX36/Qol3uRr61Ct3ARRKMI2LWLl9znQhoplLmgwdPbLFqb5Lzl667tJt7x3KZfSDjUZUSJiUaJhqUzqGMpM4WmRqV/ZkKEYJd9cdlAlUyEm+MpB34Fd4LumMFW03KOkxDAUdvMwieuZ2K7lsyeJi26kYH2Fy2bRFY+gHIUM9R8WP19uak4flwrqPoNweXKZsHPSk+hsAAcW2DpLsHCyIipyEgmbR229mSJwu5JYTWR1LBysIB8uLr0Aiu5znX50C4oEygovGT+VhXTZOCfwLixEKxpwjk0VvBWK3UfdzgGCFKOY35Y9FKyHeM7szetSclMIN1nVCU8zfsGJt0DiY2sXE2GoIQXZ2WvR/6XcECueIAcbYSuMQflBrl9dM8F33Cvs7eKudGjHYsbxL0EuLjoP5Bto2NntTX5lNNM6O4n2xYrNH/55e1dJ5JNohGFzO3JgCZwnkEwMnMf/7O8D94QyJ5y4lO1fkE20wvEozqmGdzFkzQRmwdwUQVxKQ3msnyrmz+j4iE8gn8txEvlWb0ftqQ341MydfVkJFq4QTirBzjolLyOAtkOElLXUQeOKCk="

install:
- npm install --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/prepack-publish
  on:
    tags: true
